version: '3'

services:
  # MongoDB Service
  mongo:
    image: mongo:5.0
    container_name: household-census-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=household-census
    networks:
      - app-network

  # Backend API Service
  backend:
    build:
      context: ../household-census-backend
      dockerfile: Dockerfile
    container_name: household-census-backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      # Change this - use anonymous volume to preserve node_modules
      - ../household-census-backend:/app:cached
      - /app/node_modules
      - uploads:/app/uploads
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/household-census
    networks:
      - app-network
    env_file:
      - ../household-census-backend/.env

  # Frontend Service
  frontend:
    build:
      context: ../household-census-frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://13.51.166.196/api
    container_name: household-census-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

# Volumes
volumes:
  mongo-data:
  uploads:

# Networks
networks:
  app-network:
    driver: bridge